name: ci
on: [ push, pull_request ]

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    continue-on-error: false
    timeout-minutes: 30
    strategy:
      fail-fast: false
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install rust
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: stable

      - name: "`sccache` ~ install"
        run: |
          curl $SCCACHE_URL -Lo $SCCACHE_ARCHIVE
          curl $SCCACHE_DIST_URL -Lo $SCCACHE_DIST_ARCHIVE
          tar -xvf $SCCACHE_ARCHIVE
          tar -xvf $SCCACHE_DIST_ARCHIVE
          # mv $SCCACHE_DIR/$SCCACHE_FILE $SCCACHE_FILE
          mv $SCCACHE_DIST_DIR/$SCCACHE_DIST_FILE $SCCACHE_DIR/$SCCACHE_DIST_FILE
          echo "PATH=$(pwd)/$SCCACHE_DIR:$PATH" >> $GITHUB_ENV
        env:
          SCCACHE_URL: https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz
          SCCACHE_DIST_URL: https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-dist-v0.10.0-x86_64-unknown-linux-musl.tar.gz
          SCCACHE_ARCHIVE: sccache.tar.gz
          SCCACHE_DIST_ARCHIVE: sccache-dist.tar.gz
          SCCACHE_DIR: sccache-v0.10.0-x86_64-unknown-linux-musl
          SCCACHE_DIST_DIR: sccache-dist-v0.10.0-x86_64-unknown-linux-musl
          SCCACHE_FILE: sccache
          SCCACHE_DIST_FILE: sccache-dist

      - name: "`sccache` ~ config"
        run: |
          mkdir -p $HOME/.config/sccache
          echo '[cache.disk]
          dir = "'"$HOME/.cache/sccache"'"' >  $HOME/.config/sccache/config

          echo 'public_addr = "0.0.0.0:10500"' >  $HOME/.config/sccache/scheduler-config.toml



      - name: Build
        run: cargo build --locked --release
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_LOG: debug


