name: ci
on: [ push, pull_request ]

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    continue-on-error: false
    timeout-minutes: 30
    strategy:
      fail-fast: false
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install rust
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: stable

      - name: "`sccache` ~ install"
        run: |
          git clone $SCCACHE_URL
          cd sccache
          cargo build --locked --release
          sudo mv $SCCACHE_DIR/$SCCACHE_FILE $BIN_DIR
        env:
          SCCACHE_URL: https://github.com/mozilla/sccache.git
          SCCACHE_DIR: target/release
          BIN_DIR: /usr/bin
          SCCACHE_FILE: sccache

      - name: "`sccache` ~ config"
        run: |
          mkdir -p $HOME/.config/sccache
          echo '[cache.disk]
          dir = "'"$HOME/.cache/sccache"'"' >  $HOME/.config/sccache/config

          echo 'public_addr = "0.0.0.0:10500"' >  $HOME/.config/sccache/scheduler-config.toml



      - name: Build
        run: cargo build --locked --release
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_LOG: debug


