name: ci
on: [ push, pull_request ]

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    continue-on-error: false
    timeout-minutes: 30
    strategy:
      fail-fast: false
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install rust
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: stable

      - name: "`sccache` ~ install"
        run: cargo install sccache

      - name: which
        run: which sccache

      - name: Build
        run: cargo build --locked --release
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_LOG: debug


