name: ci
on: [ push, pull_request ]

jobs:
  test:
    name: test ${{ matrix.os }} rust ${{ matrix.rustc || 'stable' }} ${{ matrix.buildserver }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        rustc: [stable, beta, nightly]
        buildserver: [local, overlay, docker]
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Clone repository
        uses: actions/checkout@v4

      - name: "Install rust"
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: ${{ matrix.rustc }}


      - name: "`sccache` ~ config"
        run: ./.github/conf.sh

      - name: "`systemd` ~ config"
        run: ./.github/systemd.sh


      - name: "`sccache` ~ install"
        run: |
          git clone $SCCACHE_URL
          cd sccache
          cargo build --locked --release --features=dist-server
          sudo mv $SCCACHE_DIR/$SCCACHE_FILE $SCCACHE_DIR/$SCCACHE_DIST_FILE $BIN_DIR
        env:
          SCCACHE_URL: https://github.com/mozilla/sccache.git
          SCCACHE_DIR: target/release
          BIN_DIR: /usr/bin
          SCCACHE_FILE: sccache
          SCCACHE_DIST_FILE: sccache-dist

      - name: "`bwrap` ~ install"
        run: sudo apt install -y --no-install-recommends bubblewrap



      - name: "`scheduler` start"
        run: sudo systemctl start sccache-scheduler


      - name: "`scheduler` status"
        run: systemctl status sccache-scheduler



      - name: "`buildserver` start"
        run: sudo systemctl start sccache-buildserver-${{ matrix.buildserver }}


      - name: "`buildserver` status"
        run: systemctl status sccache-buildserver-${{ matrix.buildserver }}


      - name: "`scheduler` test"
        run: sccache --show-stats && sccache --dist-status


      - name: Clean
        run: cargo clean

      - name: Build Sccache
        run: cargo build --locked --release
        env:
          RUSTC_WRAPPER: sccache


      - name: "`buildserver` status"
        run: systemctl status sccache-buildserver-${{ matrix.buildserver }}

      - name: "`scheduler` test"
        run: sccache --show-stats && sccache --dist-status


