name: ci
on: [ push, pull_request ]

jobs:
  test:
    name: test ${{ matrix.os }} rust ${{ matrix.rustc || 'stable' }} ${{ matrix.extra_desc }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure || false }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            rustc: stable
          # - os: ubuntu-22.04
          #   rustc: beta
          # - os: ubuntu-22.04
          #   rustc: nightly
          # - os: ubuntu-24.04
          #   rustc: stable
          # - os: macos-13
          # - os: macos-14
          # - os: windows-2019
          #   rustc: nightly
          # - os: windows-2019
          #   rustc: beta
          # - os: windows-2022
          #   rustc: nightly
          # - os: windows-2022
          #   rustc: beta
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install rust
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: ${{ matrix.rustc }}

      - name: "`sccache` ~ install"
        run: |
          curl $SCCACHE_URL -Lo $SCCACHE_ARCHIVE
          curl $SCCACHE_DIST_URL -Lo $SCCACHE_DIST_ARCHIVE
          tar -xvf $SCCACHE_ARCHIVE
          tar -xvf $SCCACHE_DIST_ARCHIVE
          # mv $SCCACHE_DIR/$SCCACHE_FILE $SCCACHE_FILE
          mv $SCCACHE_DIST_DIR/$SCCACHE_DIST_FILE $SCCACHE_DIR/$SCCACHE_DIST_FILE
          echo "PATH=$(pwd)/$SCCACHE_DIR:$PATH" >> $GITHUB_ENV
        env:
          SCCACHE_URL: https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz
          SCCACHE_DIST_URL: https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-dist-v0.10.0-x86_64-unknown-linux-musl.tar.gz
          SCCACHE_ARCHIVE: sccache.tar.gz
          SCCACHE_DIST_ARCHIVE: sccache-dist.tar.gz
          SCCACHE_DIR: sccache-v0.10.0-x86_64-unknown-linux-musl
          SCCACHE_DIST_DIR: sccache-dist-v0.10.0-x86_64-unknown-linux-musl
          SCCACHE_FILE: sccache
          SCCACHE_DIST_FILE: sccache-dist


      - name: "`bwrap` ~ install"
        run: sudo apt install -y --no-install-recommends bubblewrap

      - name: "which bwrap"
        run: which bwrap

      - name: "`sccache` ~ config"
        run: |
          mkdir -p $HOME/.config/sccache
          echo '[cache.disk]
          dir = "'"$HOME/.cache/sccache"'"
          [dist]
          # where to find the scheduler
          scheduler_url = "http://127.0.0.1:10500"
          # a set of prepackaged toolchains
          toolchains = []
          # the maximum size of the toolchain cache in bytes
          toolchain_cache_size = 5368709120
          cache_dir = "'"$HOME/.cache/sccache-dist-client"'"

          [dist.auth]
          type = "token"
          token = "preshared token"
          ' >  $HOME/.config/sccache/config

          echo 'public_addr = "0.0.0.0:10500"
          [client_auth]
          type = "token"
          token = "preshared token"

          [server_auth]
          type = "token"
          token = "preshared token"
           ' >  $HOME/.config/sccache/scheduler-config.toml

          echo '
          cache_dir = "/tmp/toolchains"
          public_addr = "127.0.0.1:10501"
          bind_address = "0.0.0.0:10501"
          scheduler_url = "http://127.0.0.1"

          [builder]
          type = "overlay"
          build_dir = "/tmp/build"
          bwrap_path = "/usr/bin/bwrap"

          [scheduler_auth]
          type = "token"
          token = "preshared token"
           ' >  $HOME/.config/sccache/buildserver-config.toml


      - name: Start scheduler
        run: sccache-dist scheduler --config $HOME/.config/sccache/scheduler-config.toml
        env:
          # SCCACHE_NO_DAEMON: 1
          SCCACHE_LOG: debug


      - name: Test scheduler
        run: sccache --show-stats && sccache --dist-status


      - name: Build
        run: cargo build --locked --release
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_LOG: debug


