name: ci
on: [ push, pull_request ]

env:
  SCCACHE_DIR: sccache/target/release
  SCCACHE_FILE: sccache
  SCCACHE_DIST_FILE: sccache-dist

jobs:
  sccache:
    name: sccache
    runs-on: ubuntu-22.04
    continue-on-error: false
    timeout-minutes: 30
    strategy:
      fail-fast: false
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: "`rust` ~ install"
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: ${{ matrix.rustc }}

      - name: "`sccache` ~ cached"
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ${{ env.SCCACHE_DIR }}/${{ env.SCCACHE_FILE }}
            ${{ env.SCCACHE_DIR }}/${{ env.SCCACHE_DIST_FILE }}
          key: ${{ runner.os }}-sccache

      - name: "`sccache` ~ install"
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone $SCCACHE_URL
          cd sccache
          cargo build --locked --release --features=dist-server
        env:
          SCCACHE_URL: https://github.com/mozilla/sccache.git

  test:
    name: test ${{ matrix.os }} rust ${{ matrix.rustc || 'stable' }} ${{ matrix.buildserver }}
    runs-on: ${{ matrix.os }}
    needs: sccache
    continue-on-error: true
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        rustc: [stable, beta, nightly]
        buildserver: [local, overlay, docker]
    env:
      RUST_BACKTRACE: 1
      SCCACHE_DIR: sccache/target/release
      SCCACHE_FILE: sccache
      SCCACHE_DIST_FILE: sccache-dist
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Clone repository
        uses: actions/checkout@v4

      - name: "`rust` ~ install"
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: ${{ matrix.rustc }}

      - name: "`sccache` ~ cached"
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ${{ env.SCCACHE_DIR }}/${{ env.SCCACHE_FILE }}
            ${{ env.SCCACHE_DIR }}/${{ env.SCCACHE_DIST_FILE }}
          key: ${{ runner.os }}-sccache


      - name: "`sccache` ~ install"
        run: sudo cp $SCCACHE_DIR/$SCCACHE_FILE $SCCACHE_DIR/$SCCACHE_DIST_FILE $BIN_DIR
        env:
          BIN_DIR: /usr/bin

      - name: "`bwrap` ~ install"
        run: sudo apt install -y --no-install-recommends bubblewrap


      - name: "`sccache` ~ config"
        run: ./.github/conf.sh

      - name: "`systemd` ~ config"
        run: ./.github/systemd.sh

      - name: "`scheduler` start"
        run: sudo systemctl start sccache-scheduler


      - name: "`scheduler` status"
        run: systemctl status sccache-scheduler


      - name: "`buildserver` start"
        run: sudo systemctl start sccache-buildserver-${{ matrix.buildserver }}


      - name: "`buildserver` status"
        run: systemctl status sccache-buildserver-${{ matrix.buildserver }}


      - name: "`scheduler` test"
        run: sccache --show-stats && sccache --dist-status


      - name: "Clean"
        run: cargo clean

      - name: "Build"
        run: cargo build --locked --release
        env:
          RUSTC_WRAPPER: sccache


      - name: "`buildserver` status"
        if: always()
        run: systemctl status sccache-buildserver-${{ matrix.buildserver }}

      - name: "`scheduler` test"
        if: always()
        run: sccache --show-stats && sccache --dist-status
